ANDROAPP-5617-mobile-ui-Horizontal-RadioButoons-and-checkboxes-resize-when-clear-button-appears
dhis2/dhis2-mobile-ui pull request #101
Opened 2023-10-11 09:32 UTC by DavidAparicioAlbaAsenjo

2023-10-12 05:18 UTC, siddh1004 commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputRadioButton.kt
>              }
@DavidAparicioAlbaAsenjo This component still change it's space. I think we need to update the Size to 48 as the size of icon is 48 too. 
<img width="781" alt="image" src="https://github.com/dhis2/dhis2-mobile-ui/assets/25721637/970ae57f-a1cf-49f9-b2dc-121b9a71929f">
<img width="779" alt="image" src="https://github.com/dhis2/dhis2-mobile-ui/assets/25721637/916043c2-3946-4b70-85d2-cd0ed5439056">

2023-10-12 05:20 UTC, siddh1004 commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputRadioButton.kt
> +                Spacer(modifier = Modifier.width(Spacing.Spacing24))
`Spacer(modifier = Modifier.width(Spacing.Spacing48))`

2023-10-12 05:20 UTC, siddh1004 commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputCheckBox.kt
> +                Spacer(modifier = Modifier.width(Spacing.Spacing24))
`Spacer(modifier = Modifier.width(Spacing.Spacing48))`

2023-10-12 05:35 UTC, siddh1004 commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputCheckBox.kt
>              }
@DavidAparicioAlbaAsenjo This component still change it's space. I think we need to update the Size to 48 as the size of icon is 48 too. 
<img width="781" alt="image" src="https://github.com/dhis2/dhis2-mobile-ui/assets/25721637/970ae57f-a1cf-49f9-b2dc-121b9a71929f">
<img width="779" alt="image" src="https://github.com/dhis2/dhis2-mobile-ui/assets/25721637/916043c2-3946-4b70-85d2-cd0ed5439056">

2023-10-12 05:35 UTC, siddh1004 requested changes

2023-10-12 05:35 UTC, siddh1004 commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputRadioButton.kt
> +                Spacer(modifier = Modifier.width(Spacing.Spacing24))
@DavidAparicioAlbaAsenjo This component still change it's space. I think we need to update the Size to 48 as the size of icon is 48 too. 
<img width="781" alt="image" src="https://github.com/dhis2/dhis2-mobile-ui/assets/25721637/970ae57f-a1cf-49f9-b2dc-121b9a71929f">
<img width="779" alt="image" src="https://github.com/dhis2/dhis2-mobile-ui/assets/25721637/916043c2-3946-4b70-85d2-cd0ed5439056">

2023-10-13 13:25 UTC, andresmr approved these changes

2023-10-13 13:33 UTC, siddh1004 approved these changes

2023-10-16 14:24 UTC, merged