ANDROAPP-5650-mobile-ui-Rectify-Input-Signature-and-Image-button-component-height
dhis2/dhis2-mobile-ui pull request #121
Opened 2023-10-25 07:28 UTC by DavidAparicioAlbaAsenjo

…ress indicator

2023-10-25 07:54 UTC, xavimolloy requested changes
Can you verify that it is implemented in the same way in InputFile and InputSignature?

2023-10-25 07:54 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/BasicInputImage.kt
> +                                        contentDescription = "Icon Button",
remember to pass the tint param otherwise it will show  the default purple color in the app

2023-10-25 11:37 UTC, andresmr approved these changes

2023-10-26 05:18 UTC, xavimolloy approved these changes

2023-10-26 05:18 UTC, merged