ANDROAPP-5714-Font-weight-of-accordian-title
dhis2/dhis2-mobile-ui pull request #136
Opened 2023-11-03 09:48 UTC by DavidAparicioAlbaAsenjo

2023-11-03 11:27 UTC, xavimolloy approved these changes

2023-11-06 09:19 UTC, andresmr requested changes

2023-11-06 09:19 UTC, andresmr commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/Sections.kt
> +        style = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.Medium),
I think that titleLarge needs to be modified it's font weight, currently is:
`   titleLarge = TextStyle(
                fontSize = 22.sp,
                lineHeight = 28.sp,
                fontFamily = provideFontResource(),
                fontWeight = FontWeight.Normal,
                color = TextColor.OnSurface,
            ),`
And in the specs is 👍🏽 
![image](https://github.com/dhis2/dhis2-mobile-ui/assets/3330344/1b45f3c0-470b-4902-8866-6a29f6bef020)
So maybe you need to change to FontWeight.Medium in the typography , right?

2023-11-07 17:24 UTC, andresmr approved these changes

2023-11-08 14:32 UTC, merged