ANDROAPP-5672-mobile-ui-org-unit-tree-component
dhis2/dhis2-mobile-ui pull request #170
Opened 2023-12-21 05:02 UTC by msasikanth

merge it after #168

2024-01-03 13:01 UTC, andresmr approved these changes

2024-01-11 07:04 UTC, xavimolloy approved these changes

2024-01-11 09:48 UTC, andresmr requested changes

2024-01-11 09:48 UTC, andresmr commented on designsystem/src/commonMain/resources/drawable/dhis2_org_tree_item_arrow_down.xml
Why adding the resource?, why don't use `KeyboardArrowDown` from the material icons library?

2024-01-11 09:48 UTC, andresmr commented on designsystem/src/commonMain/resources/drawable/dhis2_org_tree_item_arrow_right.xml
Why adding the resource?, why don't use `KeyboardArrowRight` from the material icons library?

2024-01-11 10:07 UTC, msasikanth commented on designsystem/src/commonMain/resources/drawable/dhis2_org_tree_item_arrow_down.xml
The dimens of the icon are a bit different from the material one. Both in terms of the glyph size and bounding box size. We cannot modify it the Material icons to match the design. That's why I had to import custom icons from the Figma.

2024-01-12 08:04 UTC, andresmr commented on designsystem/src/commonMain/resources/drawable/dhis2_org_tree_item_arrow_down.xml
I would algin this with @marcamsn , I think he is expecting to use the material icons, so maybe you could reach an agreement.

2024-01-12 10:38 UTC, marcamsn commented on designsystem/src/commonMain/resources/drawable/dhis2_org_tree_item_arrow_down.xml
Hi! @msasikanth, the icons (`keyboard_arrow_down` and `keyboard_arrow_right`) should be the same as the material one, since they are 24px, you should create a container box with a `8dp` padding outside the icon, so we should use them directly from the material icons library.
However, the `circle` icon it should be uploaded to the library. :) 

![image](https://github.com/dhis2/dhis2-mobile-ui/assets/14055841/a5959c7a-4ce0-41ad-aea8-d6da990ed60d)

2024-01-12 10:54 UTC, andresmr requested changes

2024-01-12 10:54 UTC, andresmr commented on designsystem/src/commonMain/resources/drawable/dhis2_org_tree_item_circle.xml
Hi @msasikanth , this circle item is indeed a new custom material icon, so it needs to be added. We are going to differentiate between the dhis2 icons and the material icons modified by us so it would be great if you rename this icon to _material_circle_outline.xml_ ?
ThankS!

2024-01-17 07:50 UTC, andresmr approved these changes

2024-01-17 08:05 UTC, andresmr requested changes

2024-01-17 08:05 UTC, andresmr commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/OrgBottomSheet.kt
Please, could you create some test for this new component?

2024-01-22 09:30 UTC, andresmr approved these changes

2024-01-24 09:39 UTC, merged