ANDROAPP-5437-mobile-ui-Check-box-Buttons
dhis2/dhis2-mobile-ui pull request #21
Opened 2023-08-11 11:52 UTC by DavidAparicioAlbaAsenjo

2023-08-14 09:19 UTC, andresmr approved these changes

2023-08-14 09:19 UTC, andresmr commented
Good job!

2023-08-16 11:05 UTC, DavidAparicioAlbaAsenjo commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobileui/designsystem/component/CheckBox.kt
> +                        .clickable { onClick(!checked) },
I think it makes more sense that only the text is clickable

2023-08-17 09:48 UTC, xavimolloy approved these changes

2023-08-17 10:51 UTC, andresmr approved these changes

2023-08-22 08:57 UTC, xavimolloy commented on common/src/commonMain/kotlin/org/hisp/dhis/common/screens/CheckboxScreen.kt
> +    Column(modifier = Modifier.padding(10.dp)) {
Here there are many nested columns, maybe you could just use ColumnComponentContainer and add Text for components description/title

2023-08-22 08:57 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/CheckBox.kt
> + * DHIS2 radio button with or without text. Wraps Material 3 [Checkbox].
Is radio button correct here? also there are other parameters that aren't used, can you update the documentation?

2023-08-22 08:57 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/CheckBox.kt
> +                Checkbox(
I notice that only the colors change if its disabled, maybe we could refactor this to call checkbox once only to avoid code duplicity

2023-08-22 08:57 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/CheckBox.kt
> +                color = if (enabled) {
could you shorthand this for better readability? i.e: if(enabled) TextColor.OnSurface else ..OnDisabled... or extract the color to a val.

2023-08-22 08:57 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/RadioButton.kt
> +        horizontalArrangement = Arrangement.spacedBy(0.dp, Alignment.Start),
hardcoded spacing

2023-08-22 09:13 UTC, xavimolloy requested changes
as per comments

2023-08-22 10:30 UTC, andresmr commented on common/src/commonMain/kotlin/org/hisp/dhis/common/App.kt
> +    var selectedOptionText by remember { mutableStateOf(currentScreen.value.name) }
I think that this was removed in `main` and only used the currentScreen

2023-08-22 11:10 UTC, xavimolloy approved these changes

2023-08-22 11:44 UTC, merged