add FAB component
dhis2/dhis2-mobile-ui pull request #210
Opened 2024-03-04 07:17 UTC by siddh1004

2024-03-04 07:24 UTC, xavimolloy approved these changes

2024-03-04 08:46 UTC, andresmr requested changes
Can you add screenshot testing?

2024-03-04 09:47 UTC, andresmr approved these changes

2024-03-05 10:39 UTC, andresmr approved these changes

2024-03-05 10:40 UTC, merged