Fill max available width of exposed dropdown menu
dhis2/dhis2-mobile-ui pull request #218
Opened 2024-03-21 09:17 UTC by msasikanth

When supporting text is set, the dropdown menu width is not matching the parent width. We are explicitly setting it to fill max width.

I have also added a sample in the `InputDropdownScreen` to test this

2024-03-21 10:51 UTC, andresmr approved these changes

2024-03-22 08:51 UTC, xavimolloy approved these changes

2024-03-28 07:56 UTC, andresmr requested changes
please, update the PR and target to **main branch**

2024-03-28 09:12 UTC, msasikanth commented
> please, update the PR and target to **main branch**

Huh, I remember doing this yesterday. Pushing the changes.

2024-03-28 09:14 UTC, closed without merging

2024-03-28 09:14 UTC, msasikanth commented
I have closed and reopened a new PR here https://github.com/dhis2/dhis2-mobile-ui/pull/225