fix dropdown indicator thickness
dhis2/dhis2-mobile-ui pull request #224
Opened 2024-03-27 13:04 UTC by siddh1004

2024-03-28 07:39 UTC, andresmr approved these changes

2024-03-28 08:02 UTC, andresmr requested changes
What do you think about creating a snapshot test for the dropdown component and it's variants to validate the design?

2024-04-02 09:16 UTC, siddh1004 commented
> What do you think about creating a snapshot test for the dropdown component and it's variants to validate the design?

Done

2024-04-02 10:12 UTC, andresmr approved these changes

2024-04-02 10:14 UTC, xavimolloy approved these changes

2024-04-08 11:26 UTC, closed without merging