Maven publish
dhis2/dhis2-mobile-ui pull request #237
Opened 2024-05-07 11:44 UTC by andresmr

2024-05-07 13:31 UTC, xavimolloy approved these changes

2024-05-08 06:32 UTC, mmmateos approved these changes

2024-05-08 07:32 UTC, vgarciabnz requested changes

2024-05-08 07:32 UTC, vgarciabnz commented on convention-plugins/src/main/kotlin/convention.publication.gradle.kts
> +    println("Version: $version")
Remove these println lines

2024-05-08 07:32 UTC, vgarciabnz commented on convention-plugins/build.gradle.kts
> +    mavenCentral()
This repo can be removed

2024-05-08 07:32 UTC, vgarciabnz commented on convention-plugins/build.gradle.kts
> +    implementation("io.github.gradle-nexus:publish-plugin:1.3.0")
This dependency can be removed

2024-05-08 09:36 UTC, vgarciabnz approved these changes

2024-05-08 09:36 UTC, merged