ANDROAPP-5442-mobile-ui-Supporting-text
dhis2/dhis2-mobile-ui pull request #24
Opened 2023-08-18 08:37 UTC by xavimolloy

2023-08-18 09:01 UTC, Balcan requested changes

2023-08-18 09:32 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobileui/designsystem/component/SupportingText.kt
> +    showMoreText: String = "Show more",
That will be the default value if they don't pass it, I asked about this and the translations will be external to the library apparently

2023-08-21 11:38 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobileui/designsystem/component/SupportingText.kt
> +    showMoreText: String = "Show more",
after discussing this, we will leave this as it is with a note to adapt it when we implement a new shared resources method, we are currently researching the best way to do this

2023-08-22 14:41 UTC, andresmr approved these changes

2023-08-23 09:20 UTC, merged