Create a Job to generate snapshots
dhis2/dhis2-mobile-ui pull request #276
Opened 2024-07-11 09:12 UTC by msasikanth

2024-07-12 06:33 UTC, andresmr requested changes
Images are not displaying and test are failing

2024-07-12 08:40 UTC, andresmr approved these changes

2024-07-12 12:20 UTC, andresmr approved these changes

2024-07-15 11:18 UTC, xavimolloy approved these changes

2024-07-17 10:52 UTC, merged