Add Expandable List Cards
dhis2/dhis2-mobile-ui pull request #283
Opened 2024-08-08 09:48 UTC by Balcan

2024-08-08 12:38 UTC, xavimolloy approved these changes

2024-08-08 13:03 UTC, ferdyrod commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/FAB.kt
> +            )*/
commented code

2024-08-08 13:05 UTC, ferdyrod approved these changes

2024-08-09 11:43 UTC, andresmr requested changes
please solve conflicts

2024-08-12 07:31 UTC, andresmr approved these changes

2024-08-13 10:51 UTC, merged