ANDROAPP-5440-mobile-ui-Checkbox-Buttons-block
dhis2/dhis2-mobile-ui pull request #31
Opened 2023-08-24 07:54 UTC by DavidAparicioAlbaAsenjo

2023-08-24 09:39 UTC, xavimolloy approved these changes

2023-08-24 09:39 UTC, xavimolloy commented on common/src/commonMain/kotlin/org/hisp/dhis/common/screens/previews/CheckboxPreview.kt
> +internal fun CheckboxBlockPreview(orientation: Orientation, content: List<CheckBoxState>) {
maybe you don't have to use the preview if it's not neccesary?

2023-08-24 09:39 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/CheckBox.kt
> +data class CheckBoxState(
Maybe naming could be better? ChackBoxData?

2023-08-25 08:06 UTC, andresmr requested changes

2023-08-25 08:06 UTC, andresmr commented on common/src/commonMain/kotlin/org/hisp/dhis/common/screens/CheckboxScreen.kt
> +            CheckBoxBlock(Orientation.VERTICAL, checkBoxesStatesVertical)
we need to know when an item is checked or uncheked

2023-08-29 11:03 UTC, andresmr approved these changes

2023-08-29 11:38 UTC, xavimolloy approved these changes

2023-08-31 17:23 UTC, merged