ANDROAPP-5500-mobile-ui-Create-Input-Long-Text
dhis2/dhis2-mobile-ui pull request #45
Opened 2023-09-05 13:42 UTC by xavimolloy

2023-09-06 06:28 UTC, andresmr requested changes
I would add a test for InputLongText file

2023-09-06 06:28 UTC, andresmr commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputLongText.kt
Shouldn't this component be tested?

2023-09-06 08:03 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputLongText.kt
You are very right! I'm already implementing it

2023-09-07 06:10 UTC, andresmr approved these changes

2023-09-07 09:14 UTC, Balcan approved these changes

2023-09-08 14:33 UTC, merged