ANDROAPP-5575-mobile-ui-Create-InputFileResource-component
dhis2/dhis2-mobile-ui pull request #94
Opened 2023-10-06 10:25 UTC by DavidAparicioAlbaAsenjo

2023-10-06 10:43 UTC, xavimolloy reviewed
Maybe add a test for the component?

2023-10-06 10:43 UTC, xavimolloy commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputFileResource.kt
> +                        text = provideStringResource("add_file"),
remember to add the add file string as a parameter so that we can manage translations from the app, and the default value can be that

2023-10-09 05:59 UTC, andresmr approved these changes

2023-10-11 06:16 UTC, andresmr approved these changes

2023-10-11 09:01 UTC, xavimolloy approved these changes

2023-10-13 13:23 UTC, andresmr approved these changes

2023-10-17 11:58 UTC, andresmr approved these changes

2023-10-18 07:32 UTC, andresmr requested changes

2023-10-18 07:32 UTC, andresmr commented on designsystem/src/commonMain/kotlin/org/hisp/dhis/mobile/ui/designsystem/component/InputFileResource.kt
> +                                maxLines = 1,
Can you reformat this to fix check style?

2023-10-19 07:11 UTC, andresmr approved these changes

2023-10-19 11:49 UTC, merged